INSTRUÇÕES SQL
*BASE
TABELA CLIENTES:
CREATE TABLE "CLIENTES" (
	"cpf_"	INTEGER NOT NULL UNIQUE,
	"nome "	TEXT NOT NULL,
	"telefone"	INTEGER NOT NULL,
	"data de nascimento"	DATE NOT NULL,
	PRIMARY KEY("cpf_")
);

TABELA FORNECEDORES
CREATE TABLE "FORNECEDORES" (
	"NOME"	TEXT NOT NULL,
	"TELEFONE"	INTEGER NOT NULL,
	"CNPJ"	INTEGER NOT NULL UNIQUE,
	"PRODUTO "	TEXT NOT NULL,
	PRIMARY KEY("CNPJ")
);

TABELA PRODUTO
CREATE TABLE "PRODUTOS" (
	"NOME PRODUTO"	TEXT NOT NULL,
	"ESTOQUE"	INTEGER NOT NULL,
	"TIPO  DE PRODUTO"	TEXT NOT NULL,
	"COD BARRAS"	INTEGER NOT NULL,
	PRIMARY KEY("COD BARRAS")
);

TABELA SERVIÇOS
CREATE TABLE "SERVIÇOS" (
	"TIPO SERVICO"	TEXT NOT NULL,
	"PRECO SERVICO"	FLOAT NOT NULL,
	"ID SERVICO"	INTEGER NOT NULL,
	"DESCRICAO SERVICO"	TEXT NOT NULL,
	PRIMARY KEY("ID SERVICO")
);

TABELA VENDAS
CREATE TABLE "VENDAS" (
	"QUANTIDADE PRODUTO"	INTEGER NOT NULL,
	"VALOR PRODUTO"	FLOAT NOT NULL,
	"COD BARRAS"	FOREIGN KEY NOT NULL,
	"CPF CLIENTE"	FOREIGN KEY NOT NULL UNIQUE
);